name: Podman test
on:
  workflow_dispatch:

jobs:
  test-eln:
    name: Test ELN
    runs-on: ubuntu-20.04
    steps:
      - name: build and install crun
        run: |
          set -eux
          git clone https://github.com/containers/crun.git
          sudo apt-get install -y make git gcc build-essential pkgconf libtool \
              libsystemd-dev libcap-dev libseccomp-dev libyajl-dev \
              go-md2man libtool autoconf python3 automake
          cd crun
          ./autogen.sh
          ./configure
          make
          sudo make install

      - name: test
        run: |
          set -eux
          sudo mv /usr/bin/runc /usr/bin/runc-test
          podman run -i --log-level=debug --rm quay.io/fedoraci/fedora:eln-x86_64 sh -exc "echo AAAAA"

  test-rawhide:
    name: Test rawhide
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: |
          set -eux
          podman run -i --log-level=debug --rm registry.fedoraproject.org/fedora:rawhide sh -exc "echo AAAAA"

  get-info:
    name: Get podman info
    runs-on: ubuntu-20.04
    steps:
      - name: get podman info
        run: |
          set -eux
          podman info --debug
          apt list podman
          podman version
          crun --version

          runc --version
          apt-cache search runc
